<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitaRepository extends EntityRepository
{
}
